services:
  - type: web
    name: mobycomps
    env: node
    region: oregon
    buildCommand: chmod +x ./build-render.sh && ./build-render.sh
    startCommand: chmod +x ./start-render.sh && ./start-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false