services:
  - type: web
    name: mobycomps
    env: node
    nodeVersion: 16
    plan: starter
    buildCommand: ./render-build.sh
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mobycomps-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false

databases:
  - name: mobycomps-db
    plan: starter