services:
  - type: web
    name: mobycomps
    env: node
    region: oregon
    buildCommand: chmod +x ./render-build.sh && ./render-build.sh
    startCommand: cd server && NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false