services:
  - type: web
    name: mobycomps
    env: node
    region: oregon  # or choose another region
    buildCommand: "./render-build.sh"
    startCommand: "./render-start.sh"
    healthCheckPath: /health/check
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: NODE_VERSION
        value: 20.x
      - key: DATABASE_URL
        sync: false  # This should be set manually via the Render dashboard