services:
  - type: web
    name: mobycomps
    env: node
    region: oregon
    buildCommand: cd client && npm install && npx vite build && cd ../server && npm install
    startCommand: cd server && NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false