services:
  - type: web
    name: prize-competition-platform
    env: docker
    dockerCommand: node dist/index.js
    plan: standard
    autoDeploy: true
    healthCheckPath: /health
    buildFilter:
      paths:
        - server/**/*
        - client/**/*
        - shared/**/*
        - Dockerfile
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCpuPercent: 80
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: prize-competition-database
          property: connectionString
      - key: PORT
        value: 8080
      - key: SESSION_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false

databases:
  - name: prize-competition-database
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: 15